### ISSUE TITLE
"Source archives" item is much too prominent on website

### ISSUE THREAD

**Issue by hnyman** [lede-project/web#11]
I find the "Source archives" item on the right-side box much too prominent. The item leads into an archive of package sources to be downloaded. Manual download of those sources is normally not necessary, so the item's presence on all web pages is much too much... The item should be moved away from the right side, or renamed to be something like "Package source backup download", or something like that.

(Similarly, there are no tweets, so why the link on every page? )

Additionally, the "Source archives" item leads into the directory https://sources.lede-project.org/ that contains quite much outdated stuff, e.g. versions of Linux, openssl, core tools (like ubox, uhttpd, netifd, odhcp\* ) since 2014. I think that the sources download site itself might need some cleanup, too.

**Comment by jow-** [comment]
Valid points. It was just fluff gathered by the guy doing the redesign to fill the box. The twitter link should stay as outages get announced there.

**Comment by jow-** [comment]
I did some changes in 7e097772398c781c96407750a83b80e4dd8f6667. If you have more specific suggestions feel free to open a PR. I think in general the situation will improve when more content is added to the site.
