### ISSUE TITLE
LEDE Docs: How to get started...

### ISSUE THREAD

**Issue by richb-hanover** [lede-project/web#18]
As a long-time user of OpenWrt, I am interested to give LEDE a try. Even though I've heard good reports elsewhere, there are several hurdles that stop me from investing my limited attention in taking my (working) router out of service and risking it with a new build.

If the first page of your Docs section (https://www.lede-project.org/docs/index.html) could address the questions below, it would show all new visitors to LEDE how easy it is to get started.
- I am successfully using OpenWrt 15.05.1 on my TP-Link, Netgear, and Witi routers. Where can I find the corresponding LEDE image? (I think the answer is to look in the appropriate section for my architecture on https://downloads.lede-project.org/snapshots/targets/ )
- Are there generic steps for installing from factory stock firmware? Are there step-by-step instructions for installing the image after I download it? (Should people simply look at the "device page" on OpenWrt site? Are there other sources of info?)
- What about an existing OpenWrt build? What generic/step-by-step instructions are available?
- What advice do you have about preserving (or not preserving) any settings from the previous install?
- Does LEDE come with LuCI built-in? Or do I have to install it separately?
- I regularly use a number of extra packages (luci-app-sqm, other SQM-related packages (especially cake), hnetd, snmpd, netperf) I see that they are not listed in the "packages" subdirectory for my architecture. Do they exist? How can I get them?
- What version is LEDE based on (CC? DD?) How compatible is it? What surprises might I encounter?

Many thanks!

**Comment by bobafetthotmail** [comment]
Disclaimer: not a LEDE/OpenWrt dev speaking here.

Afaik LEDE is a fork of OpenWrt trunk, most instructions for handling trunk still applies (this answers most of the questions).

I agree that the documentation is non-existant and should be written, I'm just saying what can be taken as a blueprint to make new docs.

I hope you are aware that you can write yourself things that will go in the main documentation, by sending pull requests here, just look at how txt files under the /docs folder are written. It's not written in HTML, it's similar to editing a wiki.

If I can also add something to the above list, I'm mostly trying to add support to a new device and between my noobness and the lack of documentation it's taking a while.

**Comment by blogic** [comment]
1) yes snapshots can be found at  https://downloads.lede-project.org/snapshots/targets/
the folder layout has been changed a little bit to unify the building of packages to ease the load on the buildbot setup

2) the steps are the same as for openwrt. there are people working on converting the TOH from the wiki to a database. this will take some time i guess as thee is a lot of data.

3) not sure what you mean, the steps are the same as for openwrt. not much has changed there.

4) should work out of the box.

5) i think the current images dont have it installed by default. i think we should change this for most images though

6) via opkg install

7) it is based on DD.

**Comment by richb-hanover** [comment]
Thanks for the info. I will try an install, write up my experience addressing my questions (above), and create a PR for the docs.

**Comment by blogic** [comment]
appreciated, if you have any questions let us know.
