### ISSUE TITLE
Development_new_device.html page not found / linking to existing pages

### ISSUE THREAD

**Issue by Borromini** [lede-project/web#30]
Commit 6a9a1014da2931eb14dfd9d414c39569e2b05b6c added a new document - development_new_device.txt - but it returns a 404 on the LEDE website (I replaced txt with html at the end). I don't know what's wrong here (or what I am doing wrong). The page does not seem to be linked to on one of the main pages, so I cannot click through to it.

In the same trend, I'd like the uci_defaults page to be linked as well, so people can click through to it, rather than needing to know the direct URL. Adding documentation is great but not very useful for others if it's not linked to...

**Comment by jow-** [comment]
Fixed with 5b024b03c3a302b6da794374587eed0bf3954972 - https://www.lede-project.org/docs/development_new_device.html

**Comment by bobafetthotmail** [comment]
@jow- with this pull request I fix the second reported issue: "newly added pages lack a link in the nav bar so they are unreachable if you don't know the link beforehand"
https://github.com/lede-project/web/pull/31

This is all very noobish stuff, I know, but we are getting there lol.
