### ISSUE TITLE
https://lede-project.org/ using StartSSL certificates

### ISSUE THREAD

**Issue by hardfalcon** [lede-project/web#43]
lede-project.org is still using X.509 certificates issued by StartSSL. This is a problem because StartSSL/Startcom has had some major fuckups recently, which have pushed Mozilla to basically throw them out in Firefox 51:

https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

downloads.lede-project.org is using certificates issued by Let's Encrypt and is thus not affected.

**Comment by victoredwardocallaghan** [comment]
I believe this can be closed now?

**Comment by lynxis** [comment]
LEDE moved to Let's Encrypt certificates.
